# Generated by Django 3.2.15 on 2023-05-08 14:24

from django.db import migrations


def fill_in_product_prices(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    for order_item in OrderProduct.objects.all().iterator():
        order_item.price = order_item.product.price
        order_item.save(update_fields=['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderproduct_price'),
    ]

    operations = [
        migrations.RunPython(fill_in_product_prices)
    ]
