# Generated by Django 3.2.15 on 2023-05-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Н', 'Необработан'), ('С', 'Сборка'), ('Д', 'Доставка'), ('В', 'Выполнен')], db_index=True, default='Н', max_length=1, verbose_name='статус заказа'),
        ),
    ]
