# Generated by Django 3.2.15 on 2023-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230512_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Э', 'Электронно'), ('Н', 'Наличностью')], db_index=True, default='Н', max_length=1, verbose_name='способ оплаты'),
        ),
    ]
