# Generated by Django 3.2.15 on 2023-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Э', 'Электронно'), ('Н', 'Наличностью')], db_index=True, max_length=1, verbose_name='способ оплаты'),
        ),
    ]
